export * as AuthRepository from "./auth/AuthRepository"
export * as SpesialisasiRepository from "./spesialisasi/SpesialisasiRepository"
export * as DoctorRepository from "./doctor/DoctorRepository"
export * as JadwalDokterSpesialisasiRepository from "./jadwal-dokter/jadwalDokterSpesialisasiRepository"
export * as PatientRepository from "./patient/PatientRepository"
export * as JadwalDokterUmumRepository from "./jadwal-dokter/jadwalDokterUmumRepository"
export * as ReservasiRepository from "./reservasi/ReservasiRepository"

export * as PublicSpesialisasiRepository from "./public/SpesialisasiRepository"
export * as PublicJadwalDokterSpesialisasiRepository from "./public/JadwalDokterSpesialisasiRepository"
export * as PublicJadwalDokterUmumRepository from "./public/JadwalDokterUmumRepository"
export * as PublicReservasiRepository from "./public/ReservasiRepository"
export * as PublicRiwayatRepository from "./public/RiwayatRepository"

export * as FooterRepository from "./footer/FooterRepository"
export * as AdminRepository from "./admin/AdminRepository"
